### ISSUE TITLE
Crash during RMextract step?

### ISSUE THREAD

**Issue by yesthisisalex** [lofar-astron/prefactor#275] opened 2020-07-28 07:56 UTC
Hi,
I am trying to run target pipeline on CEP3, but my pipeline constantly crashes on RMextract step (I think). 
I'm attaching my .log file, thank you for any help!

[pipeline.log](https://github.com/lofar-astron/prefactor/files/4986761/pipeline.log)

**Comment by lmorabit** [comment] 2020-07-29 12:12
It could be that some of the GPS data doesn't cover one of your antennas and/or time slots?  Perhaps it's useful to try to open the IONEX data that was downloaded ... maybe @darafferty or @maaijke or @adrabent would know more?

**Comment by adrabent** [comment] 2020-07-29 13:26
@yesthisisalex 
I tried to run from your data on lof007: `/data007/scratch/wolowska/target`
I took the first 10 SBs and started the target pipeline. In my case it does not crash at the RMextract step. Could you try to run the target pipeline from scratch again?

**Comment by yesthisisalex** [comment] 2020-07-29 14:12
@lmorabit - there is a file, but I'm not sure what to look for in it
@adrabent - I did, but I get the same errors. Is it possible that I'm missing something trivial? Not loading some essential modules or something like that? If you're able to run pipeline using my prefactor files, then maybe it is some stupid mistake. Could you tell me in detail how you do it?

**Comment by adrabent** [comment] 2020-07-29 14:43
I am using the most recent master branch of prefactor.
My environment can be loaded at CEP3:
`. /home/drabent/load_env.sh` 

I was only changing the target input pattern and the cal_solutions path matching your `cal_solutions.h5` in `/data007/scratch/wolowska/cal/Pre-Facet-Calibrator/results/cal_values/cal_solutions.h5`

Everything else is kept as default.

**Comment by lmorabit** [comment] 2020-07-29 14:53
I suspect this is a python 2 vs. python 3 issue then. The lofar-vlbi pipeline is only tested against prefactor commit 7e9103d10c8e37ee2ac2203b678af295ed03e4fd .

**Comment by yesthisisalex** [comment] 2020-07-29 20:58
Thanks for all your replies!

Is python version an issue I can deal with myself? 
I am also not sure how do I check the gps coverage - do you have any advice?

@adrabent - I was using this version https://github.com/lmorabit/prefactor because of updated models, but I have also tried this one here - https://github.com/lofar-astron/prefactor.git  but both of them give me same errors

Also this error is not understandable for me - `ERROR:node.lof007.control.lofar.python_plugin:Array objects cannot currently deal with void, unicode or object arrays
` - is it a part of the python version issue?

**Comment by tikk3r** [comment] 2020-07-30 07:35
Are home directories publicly readable on CEP 3?

Looking at the log I see that there are mixed RMextract entries between `PYTHONPATH` and `PATH`:
PYTHONPATH: /home/drabent/RMextract/lib64/python2.7/site-packages:/opt/cep/rmextract/RMextract-0.3/lib64/python2.7/site-packages
PATH: /opt/cep/rmextract/RMextract-0.3/bin

I think there are no direct calls to anything from the RMextract bin folder during prefactor, so my first guess would be that you maybe cannot access /home/drabent/RMextract and it therefore falls back to the package in /opt/cep/rmextract. If that is the same 0.3 as the 0.3 release on github, it's almost 2 years old.

If you indeed cannot access @adrabent's install (should be checkable with a simple `ls /home/drabent/RMextract`), then I suggest to try and install the latest RMextract yourself locally and to add that path to your

**Comment by yesthisisalex** [comment] 2020-07-30 07:52
I have no problem doing 'ls' on /home/drabent/RMextract - I have access to everything there

**Comment by tikk3r** [comment] 2020-07-30 08:32
Well that rules that out then. What does `python --version` report for you?

**Comment by yesthisisalex** [comment] 2020-07-30 08:33
It reports `Python 2.7.5
`

**Comment by adrabent** [comment] 2020-07-30 09:35
@yesthisisalex 
I guess @tikk3r  is right. If you load my environment file you should not have any entries like /opt/cep/rmextract/RMextract-0.3/bin` in your PATH. Please log out and log in again to the node. Only source my environment file and run the target pipeline from scratch again. Just to be on the same page and to avoid some unwanted interference of the software.

**Comment by yesthisisalex** [comment] 2020-07-30 10:02
Yes, there is a difference after logging out

It was:
`'PYTHONPATH': '/home/drabent/RMextract/lib64/python2.7/site-packages:/home/drabent/losoto:/opt/cep/casacore/builds/python-casacore-2.1.2-2.3.0/lib64/python2.7/site-packages:/opt/cep/pybdsf/PyBDSF-1.8.13/lib64/python2.7/site-packages:/opt/cep/lofar/lofar_versions/LOFAR-Release-3_2_0/lofar_build/install/gnucxx11_opt/lib64/python2.7/site-packages:/opt/cep/lsmtool/LSMTool-1.2.0:/opt/cep/rmextract/RMextract-0.3/lib64/python2.7/site-packages'`
Now it is:
`'PYTHONPATH': '/home/drabent/RMextract/lib64/python2.7/site-packages:/home/drabent/losoto:/opt/cep/casacore/builds/python-casacore-2.1.2-2.3.0/lib64/python2.7/site-packages:/opt/cep/pybdsf/PyBDSF-1.8.13/lib64/python2.7/site-packages:/opt/cep/lofar/lofar_versions/LOFAR-Release-3_2_0/lofar_build/install/gnucxx11_opt/lib64/python2.7/site-packages:/opt/cep/lsmtool/LSMTool-1.2.0'`

Same with PATH:

the old one:
`'PATH': '/home/drabent/dysco/bin:/home/drabent/aoflagger/bin:/home/drabent/losoto/bin:/opt/cep/dp3/20190206/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/cep/casacore/builds/casacore-2.3.0/build/gnucxx11_opt/bin:/opt/cep/casacore/builds/casarest-1.4.2-2.3.0/casarest-1.4.2/build/gnucxx11_opt/bin:/opt/cep/aoflagger/aoflagger-2.10.0/build/bin:/opt/cep/pybdsf/PyBDSF-1.8.13/bin:/opt/cep/dysco/dysco-1.1/build/bin:/opt/cep/lofar/lofar_versions/LOFAR-Release-3_2_0/lofar_build/install/gnucxx11_opt/bin:/opt/cep/lofar/lofar_versions/LOFAR-Release-3_2_0/lofar_build/install/gnucxx11_opt/sbin:/opt/cep/lsmtool/LSMTool-1.2.0/bin:/opt/cep/wsclean/wsclean-2.8/bin:/opt/cep/rmextract/RMextract-0.3/bin'`

and the new one:
`'PATH': '/home/drabent/dysco/bin:/home/drabent/aoflagger/bin:/home/drabent/losoto/bin:/opt/cep/dp3/20190206/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/cep/casacore/builds/casacore-2.3.0/build/gnucxx11_opt/bin:/opt/cep/casacore/builds/casarest-1.4.2-2.3.0/casarest-1.4.2/build/gnucxx11_opt/bin:/opt/cep/aoflagger/aoflagger-2.10.0/build/bin:/opt/cep/pybdsf/PyBDSF-1.8.13/bin:/opt/cep/dysco/dysco-1.1/build/bin:/opt/cep/lofar/lofar_versions/LOFAR-Release-3_2_0/lofar_build/install/gnucxx11_opt/bin:/opt/cep/lofar/lofar_versions/LOFAR-Release-3_2_0/lofar_build/install/gnucxx11_opt/sbin:/opt/cep/lsmtool/LSMTool-1.2.0/bin:/opt/cep/wsclean/wsclean-2.8/bin'`

But the pipeline crashes at the same step, with the same errors

**Comment by adrabent** [comment] 2020-07-30 15:36
Could you please check whether you run it also with the current master branch?
I just checked in your home-directory that your `createRMh5parm.py` is from an older version.

**Comment by yesthisisalex** [comment] 2020-07-30 19:40
I download it to my home folder by using `git clone https://github.com/lofar-astron/prefactor.git` - it should copy the current master branch to the node, right? 
You have mentioned that you successfully ran the pipeline using my data. Did you just use prefactor that is currently in your /home on cep3? I don't see any difference between my 'createRMh5parm.py' and yours. 

I'm a little bit confused - I clone the git repo, I only change three things in .parset - directory of my data, filename pattern, and location of cal_solutions.h5. Then I change only runtime directory for mine in pipeline.cfg. it is impossible that I have messed something up with files, because I literally haven't changed anything else, and it crashes with this bizarre error about "void, unicode and arrays" over and over again. What is wrong with what I'm doing? :)

**Comment by adrabent** [comment] 2020-07-31 08:39
>  I don't see any difference between my 'createRMh5parm.py' and yours.

Yesterday there was a difference. Today there isn't. You might have overwritten the local copy properly.

>  it is impossible that I have messed something up with files, because I literally haven't changed anything else

Nothing is impossible, but in terms of configuration and all the information you could provide I am not able to reproduce this error and thus can not fix it.

**Comment by adrabent** [comment] 2020-08-04 08:41
Installing `pip install --upgrade --user "tables<3.6"` solved the problem on CEP3.

**Closed by adrabent** 2020-08-04 08:41 UTC
