### ISSUE TITLE
pythonplugin failed in Initial Subtraction

### ISSUE THREAD

**Issue by botteon** [lofar-astron/prefactor#123] opened 2017-02-14 16:56 UTC
Hi,
I have the following error in the Initial-Subtraction

```
/opt/lofar/lib/python2.7/site-packages/lofarpipe/support/utilities.pyc : Using default subprocess module!
Reading configuration file: pipeline.cfg
Reading task definition file(s): /opt/lofar/share/pipeline/tasks.cfg
2017-02-10 09:53:20 DEBUG   genericpipeline: Pipeline start time: 2017-02-10T08:53:20
2017-02-10 09:53:20 INFO    genericpipeline: LOFAR Pipeline (Initial-Subtract1-4) starting.
2017-02-10 09:53:20 INFO    genericpipeline: SASID = , MOMID = , Feedback method = messagebus
NYI: validate_steps
log4cplus:ERROR No appenders could be found for logger (LCS.Common.EXCEPTION).
log4cplus:ERROR Please initialize the log4cplus system properly.
2017-02-10 09:53:21 INFO    genericpipeline: Beginning step create_ms_map
2017-02-10 09:53:21 INFO    genericpipeline: Beginning step combine_mapfile
FILE:  ['/data/botteon/a781/prefactor/results1-4/L561383_SB001_uv.pre-cal_12944FA62t_121MHz.pre-cal.ms', '/data/botteon/a781/prefactor/results1-4/L561383_SB011_uv.pre-cal_12944FA62t_123MHz.pre-cal.ms', '/data/botteon/a781/prefactor/results1-4/L561383_SB021_uv.pre-cal_12944FA62t_125MHz.pre-cal.ms', '/data/botteon/a781/prefactor/results1-4/L561383_SB031_uv.pre-cal_12944FA62t_127MHz.pre-cal.ms']
2017-02-10 09:53:21 INFO    genericpipeline: Beginning step do_magic
2017-02-10 09:53:21 INFO    genericpipeline: Running task: pythonplugin
/opt/lofar/lib/python2.7/site-packages/lofarpipe/support/subprocessgroup.pyc : Using default subprocess module!
2017-02-10 09:53:21 INFO    genericpipeline.executable_args: recipe executable_args started
2017-02-10 09:53:21 INFO    genericpipeline.executable_args: Starting /opt/prefactor/scripts/InitSubtract_deep_sort_and_compute.py run
Reading configuration file: pipeline.cfg
Reading task definition file(s): /opt/lofar/share/pipeline/tasks.cfg
2017-02-10 09:53:21 DEBUG   genericpipeline.executable_args: Pipeline start time: 2017-02-10T08:53:20
2017-02-10 09:53:21 INFO    genericpipeline.executable_args: Limiting to 1 simultaneous jobs/node
2017-02-10 09:53:21 DEBUG   genericpipeline.executable_args: Job dispatcher at 127.0.1.1:41406
2017-02-10 09:53:21 INFO    genericpipeline.executable_args: ********************** Remote method is local
2017-02-10 09:53:21 INFO    genericpipeline.executable_args: Waiting for compute threads...
2017-02-10 09:53:21 INFO    genericpipeline.executable_args: Subprocess starting: /bin/sh -c python /opt/lofar/lib/python2.7/site-packages/lofarpipe/recipes/nodes/python_plugin.py 0 127.0.1.1 41406 (['/bin/sh', '-c', 'python /opt/lofar/lib/python2.7/site-packages/lofarpipe/recipes/nodes/python_plugin.py 0 127.0.1.1 41406'])
2017-02-10 09:53:21 WARNING genericpipeline.executable_args: /opt/lofar/lib/python2.7/site-packages/lofarpipe/support/utilities.pyc : Using default subprocess module!
2017-02-10 09:53:21 DEBUG   genericpipeline.executable_args: Request for job 0 from ('127.0.0.1', 33400)
2017-02-10 09:53:21 DEBUG   node.lofar.python_plugin: infile            = ['/data/botteon/a781/prefactor/results1-4/L561383_SB001_uv.pre-cal_12944FA62t_121MHz.pre-cal.ms', '/data/botteon/a781/prefactor/results1-4/L561383_SB011_uv.pre-cal_12944FA62t_123MHz.pre-cal.ms', '/data/botteon/a781/prefactor/results1-4/L561383_SB021_uv.pre-cal_12944FA62t_125MHz.pre-cal.ms', '/data/botteon/a781/prefactor/results1-4/L561383_SB031_uv.pre-cal_12944FA62t_127MHz.pre-cal.ms']
2017-02-10 09:53:21 DEBUG   node.lofar.python_plugin: executable        = /opt/prefactor/scripts/InitSubtract_deep_sort_and_compute.py
2017-02-10 09:53:21 DEBUG   node.lofar.python_plugin: working directory = /data/botteon/a781/products/Initial-Subtract1-4
2017-02-10 09:53:21 DEBUG   node.lofar.python_plugin: arguments         = ["['/data/botteon/a781/prefactor/results1-4/L561383_SB001_uv.pre-cal_12944FA62t_121MHz.pre-cal.ms', '/data/botteon/a781/prefactor/results1-4/L561383_SB011_uv.pre-cal_12944FA62t_123MHz.pre-cal.ms', '/data/botteon/a781/prefactor/results1-4/L561383_SB021_uv.pre-cal_12944FA62t_125MHz.pre-cal.ms', '/data/botteon/a781/prefactor/results1-4/L561383_SB031_uv.pre-cal_12944FA62t_127MHz.pre-cal.ms']"]
2017-02-10 09:53:21 DEBUG   node.lofar.python_plugin: arg dictionary    = {'cellsize_lowres_deg': '0.00694', 'fieldsize_lowres': '6.5', 'outmapname': 'do_magic.datamap', 'y_axis_stretch': '1.', 'image_padding': '1.4', 'fieldsize_highres': '2.5', 'cellsize_highres_deg': '0.00208', 'mapfile_dir': '/data/botteon/a781/runtime/Initial-Subtract1-4/mapfiles'}
2017-02-10 09:53:21 DEBUG   node.lofar.python_plugin: environment       = {'LOFARDATAROOT': '/opt/lofar/data', 'SAS_CCFPATH': '/irasoft/sas_15.0/ccf', 'PYTHONPATH': '/opt/jinja2/lib/python2.7/site-packages/:/opt/matplotlib/lib/python2.7/site-packages/:/opt/LSMTool/:/opt/shapely/lib/python2.7/site-packages/:/opt/astropy/lib/python2.7/site-packages/:/opt/lofar/lib/python2.7/site-packages/:/opt/factor/:/opt/RMextract/:/opt/python-casacore/python-casacore/::/opt/lofar/lib/python2.7/site-packages:/irasoft/heasoft/heasoft-6.18/x86_64-unknown-linux-gnu-libc2.12/lib/python:/irasoft/heasoft/heasoft-6.18/x86_64-unknown-linux-gnu-libc2.12/lib:/opt/python-casacore/lib/python2.7/site-packages/', 'OMP_NUM_THREADS': '8', 'LOFARROOT': '/opt/lofar', 'PATH': ':/opt/lofar/sbin:/opt/lofar/bin:/irasoft/heasoft/heasoft-6.18/x86_64-unknown-linux-gnu-libc2.12/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/casacore/bin:/opt/prefactor/bin/:/opt/factor/bin/:/opt/LSMTool/bin/:/opt/wsclean/bin', 'LD_LIBRARY_PATH': ':::/opt/lofar/lib:/irasoft/heasoft/heasoft-6.18/x86_64-unknown-linux-gnu-libc2.12/lib:/opt/casacore/lib:/opt/cfitsio/lib:/opt/wsclean/lib'}
2017-02-10 09:53:21 INFO    node.lofar.python_plugin: Processing ['/data/botteon/a781/prefactor/results1-4/L561383_SB001_uv.pre-cal_12944FA62t_121MHz.pre-cal.ms', '/data/botteon/a781/prefactor/results1-4/L561383_SB011_uv.pre-cal_12944FA62t_123MHz.pre-cal.ms', '/data/botteon/a781/prefactor/results1-4/L561383_SB021_uv.pre-cal_12944FA62t_125MHz.pre-cal.ms', '/data/botteon/a781/prefactor/results1-4/L561383_SB031_uv.pre-cal_12944FA62t_127MHz.pre-cal.ms']
2017-02-10 09:53:26 DEBUG   genericpipeline.executable_args: InitSubtract_sort_and_compute.py: Putting files into bands.
2017-02-10 09:53:26 DEBUG   genericpipeline.executable_args: Results for job 0 submitted by ('127.0.0.1', 33404)
2017-02-10 09:53:26 ERROR   node.lofar.python_plugin: global name 'self' is not defined
2017-02-10 09:53:26 INFO    node.lofar.python_plugin: Total time 4.6003s; user time: 4.4360s; system time: 0.1200s
2017-02-10 09:53:26 DEBUG   node.lofar.python_plugin: Start time was 1486716801.4521s; end time was 1486716806.0525s
2017-02-10 09:53:27 DEBUG   genericpipeline.executable_args: 
2017-02-10 09:53:27 WARNING genericpipeline.executable_args: 
2017-02-10 09:53:27 INFO    genericpipeline.executable_args: Subprocess completed with exit status 1: /bin/sh -c python /opt/lofar/lib/python2.7/site-packages/lofarpipe/recipes/nodes/python_plugin.py 0 127.0.1.1 41406
2017-02-10 09:53:27 ERROR   genericpipeline.executable_args: Remote process python /opt/lofar/lib/python2.7/site-packages/lofarpipe/recipes/nodes/python_plugin.py ["['/data/botteon/a781/prefactor/results1-4/L561383_SB001_uv.pre-cal_12944FA62t_121MHz.pre-cal.ms', '/data/botteon/a781/prefactor/results1-4/L561383_SB011_uv.pre-cal_12944FA62t_123MHz.pre-cal.ms', '/data/botteon/a781/prefactor/results1-4/L561383_SB021_uv.pre-cal_12944FA62t_125MHz.pre-cal.ms', '/data/botteon/a781/prefactor/results1-4/L561383_SB031_uv.pre-cal_12944FA62t_127MHz.pre-cal.ms']", '/opt/prefactor/scripts/InitSubtract_deep_sort_and_compute.py', ["['/data/botteon/a781/prefactor/results1-4/L561383_SB001_uv.pre-cal_12944FA62t_121MHz.pre-cal.ms', '/data/botteon/a781/prefactor/results1-4/L561383_SB011_uv.pre-cal_12944FA62t_123MHz.pre-cal.ms', '/data/botteon/a781/prefactor/results1-4/L561383_SB021_uv.pre-cal_12944FA62t_125MHz.pre-cal.ms', '/data/botteon/a781/prefactor/results1-4/L561383_SB031_uv.pre-cal_12944FA62t_127MHz.pre-cal.ms']"], {'cellsize_lowres_deg': '0.00694', 'fieldsize_lowres': '6.5', 'fieldsize_highres': '2.5', 'y_axis_stretch': '1.', 'image_padding': '1.4', 'outmapname': 'do_magic.datamap', 'cellsize_highres_deg': '0.00208', 'mapfile_dir': '/data/botteon/a781/runtime/Initial-Subtract1-4/mapfiles'}, '/data/botteon/a781/products/Initial-Subtract1-4', False, {'args_format_option_argument': '=', 'args_format_option': '-', 'args_format': 'gnu', 'args_formatlongoption': '--', 'args_format_argument': ''}, {'LOFARDATAROOT': '/opt/lofar/data', 'SAS_CCFPATH': '/irasoft/sas_15.0/ccf', 'PYTHONPATH': '/opt/jinja2/lib/python2.7/site-packages/:/opt/matplotlib/lib/python2.7/site-packages/:/opt/LSMTool/:/opt/shapely/lib/python2.7/site-packages/:/opt/astropy/lib/python2.7/site-packages/:/opt/lofar/lib/python2.7/site-packages/:/opt/factor/:/opt/RMextract/:/opt/python-casacore/python-casacore/::/opt/lofar/lib/python2.7/site-packages:/irasoft/heasoft/heasoft-6.18/x86_64-unknown-linux-gnu-libc2.12/lib/python:/irasoft/heasoft/heasoft-6.18/x86_64-unknown-linux-gnu-libc2.12/lib:/opt/python-casacore/lib/python2.7/site-packages/', 'OMP_NUM_THREADS': '8', 'LOFARROOT': '/opt/lofar', 'PATH': ':/opt/lofar/sbin:/opt/lofar/bin:/irasoft/heasoft/heasoft-6.18/x86_64-unknown-linux-gnu-libc2.12/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/casacore/bin:/opt/prefactor/bin/:/opt/factor/bin/:/opt/LSMTool/bin/:/opt/wsclean/bin', 'LD_LIBRARY_PATH': ':::/opt/lofar/lib:/irasoft/heasoft/heasoft-6.18/x86_64-unknown-linux-gnu-libc2.12/lib:/opt/casacore/lib:/opt/cfitsio/lib:/opt/wsclean/lib'}] failed on localhost
2017-02-10 09:53:27 DEBUG   genericpipeline.executable_args: compute.dispatch results job 0: job_duration: 5.96911811829, returncode: 1 
2017-02-10 09:53:28 DEBUG   genericpipeline.executable_args: Adding node_logging_information
2017-02-10 09:53:28 ERROR   genericpipeline.executable_args: All jobs failed. Bailing out!
2017-02-10 09:53:28 WARNING genericpipeline.executable_args: Note: recipe outputs are not complete
2017-02-10 09:53:28 WARNING genericpipeline.executable_args: recipe executable_args completed with errors
2017-02-10 09:53:28 WARNING genericpipeline: pythonplugin reports failure (using executable_args recipe)
2017-02-10 09:53:28 ERROR   genericpipeline: *******************************************
2017-02-10 09:53:28 ERROR   genericpipeline: Failed pipeline run: Initial-Subtract1-4
2017-02-10 09:53:28 ERROR   genericpipeline: Detailed exception information:
2017-02-10 09:53:28 ERROR   genericpipeline: <class 'lofarpipe.support.lofarexceptions.PipelineRecipeFailed'>
2017-02-10 09:53:28 ERROR   genericpipeline: pythonplugin failed
2017-02-10 09:53:28 ERROR   genericpipeline: *******************************************
```

I don't know if this is a problem with the genericpipeline as this if the first test I run on a new node.
Please also notice that the process remains active in the terminal without using any resource.

**Comment by AHorneffer** [comment] 2017-02-14 17:39
>  Please also notice that the process remains active in the terminal without using any resource.

What do you mean with that?

Anyhow, it fails after printing:
> InitSubtract_sort_and_compute.py: Putting files into bands.  

but apparently before running:
```
print "InitSubtract_sort_and_compute.py: Working on Band:",band.name
```
with the error message:
> global name 'self' is not defined

I don't really see what could cause this error.
Is the script `InitSubtract_deep_sort_and_compute.py`the same as on GitHub?
Does Factor work on that cluster? (If it is a problem with the OS, then I would expect it to fail in a similar way.)

You could also try running the script manually:
```
import InitSubtract_deep_sort_and_compute
main(['/data/botteon/a781/prefactor/results1-4/L561383_SB001_uv.pre-cal_12944FA62t_121MHz.pre-cal.ms', '/data/botteon/a781/prefactor/results1-4/L561383_SB011_uv.pre-cal_12944FA62t_123MHz.pre-cal.ms', '/data/botteon/a781/prefactor/results1-4/L561383_SB021_uv.pre-cal_12944FA62t_125MHz.pre-cal.ms', '/data/botteon/a781/prefactor/results1-4/L561383_SB031_uv.pre-cal_12944FA62t_127MHz.pre-cal.ms'],outmapname='test.datamap',mapfile_dir='.', cellsize_lowres_deg='0.00694', fieldsize_lowres='6.5', y_axis_stretch='1.', image_padding='1.4', fieldsize_highres='2.5', cellsize_highres_deg='0.00208')
```

**Comment by darafferty** [comment] 2017-02-14 18:31
Looks like the problem is likely in line 311 of https://github.com/lofar-astron/prefactor/blob/master/scripts/InitSubtract_deep_sort_and_compute.py:

`int_time_sec = self.timestep_sec * timestep`

**Comment by AHorneffer** [comment] 2017-02-15 09:50
O.K. Thanks. I guess it is fixed now.

Please re-open if needed.

**Closed by AHorneffer** 2017-02-15 09:50 UTC
