### ISSUE TITLE
Prefactor v3.0 pipeline on Target data finishes successfully but gives message TypeError: set() takes exactly 1 argument (3 given)

### ISSUE THREAD

**Issue by pommierm** [lofar-astron/prefactor#222] opened 2019-03-15 08:06 UTC
Prefactor v3.0 run on the target data finished successfully but end with a message:

2019-03-14 23:33:44 WARNING genericpipeline.executable_args: DEBUG:node.lof005.control.lofar.python_plugin:Start time was 1552606424.3553s; end time was 1552606424.5839s
2019-03-14 23:33:44 DEBUG   genericpipeline.executable_args: Results for job 0 submitted by ('10.144.5.107', 58044)
2019-03-14 23:33:44 INFO    node.lof005.control.lofar.python_plugin: Total time 0.2282s; user time: 0.1936s; system time: 0.6772s
2019-03-14 23:33:44 DEBUG   node.lof005.control.lofar.python_plugin: Start time was 1552606424.3553s; end time was 1552606424.5839s
2019-03-14 23:33:44 INFO    genericpipeline.executable_args: Waiting for compute threads...
2019-03-14 23:33:45 DEBUG   genericpipeline.executable_args:
2019-03-14 23:33:45 WARNING genericpipeline.executable_args:
2019-03-14 23:33:45 INFO    genericpipeline.executable_args: Subprocess completed with exit status 0: /bin/sh -c python /opt/cep/lofim/daily/Thu/lofar_build/install/gnucxx11_opt/lib64/python2.7/site-packages/lofarpipe/recipes/nodes/python_plugin.py 0 10.144.5.107 49038
2019-03-14 23:33:45 DEBUG   genericpipeline.executable_args: compute.dispatch results job 0: job_duration: 1.28226804733, returncode: 0
2019-03-14 23:33:46 DEBUG   genericpipeline.executable_args: Adding node_logging_information
2019-03-14 23:33:46 DEBUG   genericpipeline.executable_args: Writing data map file: /data022/scratch/mp/working_directory//Pre-Facet-Target/mapfiles/h5parm_name.mapfile
2019-03-14 23:33:46 INFO    genericpipeline.executable_args: recipe executable_args completed
2019-03-14 23:33:46 INFO    genericpipeline: LOFAR Pipeline finished succesfully.
2019-03-14 23:33:46 INFO    genericpipeline: recipe genericpipeline completed
Results:
Process PoolWorker-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 261, in _bootstrap
    util._exit_function()
  File "/usr/lib64/python2.7/multiprocessing/util.py", line 317, in _exit_function
    for p in active_children():
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 70, in active_children
    return list(_current_process._children)
TypeError: set() takes exactly 1 argument (3 given)
Closing remaining open files:/data022/scratch/mp/working_directory//Pre-Facet-Target/results/cal_values/solutions.h5...done

Please let me know how to fix this error message.

Thanks

**Comment by adrabent** [comment] 2020-06-02 15:41
Issue is a duplicate of #233

**Closed by adrabent** 2020-06-02 15:41 UTC
